spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MYSQL    # H2 DB 사용
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create    # create
